---
title: "Master_Thesis"
editor: visual
bibliography: references.bib
---

# Abstract

This thesis uses a novel data set to investigate the relationship between entry and exit of newspapers and electoral participation in Swiss federal elections 1848-1955. Exploiting the variation in net entries of newspapers within election years between cantons I find that the net entry of one or more newspapers has a significant positive impact on electoral participation. The impact is larger for political newspapers. German language newspapers exert a positive and significant effect whereas for French language newspapers no significance can be established. Even stronger positive effects are detected when specifying German political and weekly newspapers. I also show that liberal newspapers were especially important for inducing electoral participation. The effect is positive and significant before 1917 but vanishes after the introduction of the proportional voting system in 1919. The results are limited to the inclusion of the top-newspaper-cantons Bern, Vaud and Zürich indicating that the impact of newspapers on voter turnout is largely driven by these cantons.

# **Introduction**

A well-functioning independent press has been seen as a vital element of modern democracies [@drago2013]. In the field of political science there is a long tradition in viewing the media as an essential part of informing the general public about political affairs. Among all media types, specially newspapers were historically attributed an impact on public opinion and electoral outcomes. Various aspects of newspapers' influence have been covered in previous literature: Schaffner [-@schaffner2006] studies the impact of newspapers on incumbent advantage. Ferraz and Finan [-@ferraz2008] and Snyder and Strömberg [-@snyder2010] investigate the relationship between newspaper and political accountability. And Gerber, Karlan and Bergan [-@gerber2009] examine the effect of newspapers' support for certain parties and political opinion.

Besides an extensive literature on the relationship of media on political participation [@gentzkow2006; @oberholzer-gee2009; @gentzkow2011; @perlman2016], a growing number of empirical literature is specifically concerned about newspapers and electoral participation.

Chapp and Aehl [-@chapp2021] investigate the effect of declining circulation rates of newspapers in US local elections. They find evidence that newspaper have an influence on how thoroughly voters fill out their ballot. Lee and Wei [-@lee2008] find that the decrease of US newspaper readership among young adults is associated with a decrease in political participation. Arendt and Brantner [-@arendt2015] look at the effect of "quality" press on the 2014 EU parliamentary elections and conclude that the exposure to this type of media increases turnout through the mediation of knowledge and efficacy.

Within this field of literature, the special case of newspaper entry and exit has recently been investigated in US, Italian and Swiss markets.\

Gentzkow, Shapiro and Sinkinson [-@gentzkow2011] look at the entry and exit of US daily newspapers between the years 1869-1924 when newspapers held a dominant position in terms of political information. They explore the impact of the entry and exit on political participation as well as party vote share and electoral competitiveness. Their findings suggest that newspapers have a significant positive effect on participation which however decreases as the second, third or following newspaper are observed. Drago, Nannicina and Sobbrio [-@drago2014] evaluate the effect of newspaper entry and exit in Italian cities between 1993-2010. Using a similar methodology to Gentzkow et al. [-@gentzkow2011] , they find evidence that the net entry of newspapers increases turnout in municipal elections, the reelection probability of incumbent mayors, as well as the efficiency of municipal government.

Muth and Nguyen (2021) investigate the impact of newspaper entry and exit on electoral participation and party vote share in Swiss federal elections between the years 1896-1917. Using a data set of 1,466 Swiss newspapers and 49 constituencies, they find evidence for a positive relationship between newspapers and turnout. They also find that the political influence of newspapers varies depending on the newspaper's languages.\

In this thesis, I pose related questions for a longer time period: What impact does the entry and exit of newspapers have on voter turnout in Switzerland between 1848 and 1955? And does this impact vary over different newspaper groups and time? Despite the recent study on the subject, there is no long term study which utilizes the newspaper lexicon "Bibliography der Schweizer Presse" by Fritz Blaser which comprises the years 1650-1958. This enables me to conduct an analysis of a much larger time span. Applying a similar methodology and reasoning as is in the above mentioned studies I formulate my main hypothesis:

**Main hypothesis** More informed citizens tend to vote more often. If newspapers inform the general public, then a higher number of newspapers should induce a higher voter turnout.

Other factors may also play a role when investigating the relationship between newspapers and turnout. Generally, some specific newspapers might be more likely to inform the general public about affairs relevant for their increased voting behavior. So, a higher presence of these newspapers could then induce a higher voter turnout. In the following I will consider important aspects of these newspaper subgroups

1.  **Political vs. non-political:** Political newspapers might be more able to induce citizens to vote [@kübler2018]. On the flip side, non-political newspapers might not play this informational role and could therefore miss to engage citizens. For the Swiss case, Muth and Nguyen (2021) find significant evidence for a positive relationship between political newspapers and turnout. In contrast, non-political newspapers even show a negative, though insignificant coefficient.

2.  **Language**: Switzerland is a multilingual nation with German and French being the most common languages. Muth and Nguyen (2021) show that variation in newspaper's effect is present if languages are distinguished. They specifically look at German and French political newspapers where a significant positive relationship is detected for the German but not for the French ones. This might be explained through content-presentational front page variations between these newspapers (Muth and Nguyen, 2021, p. 11).

3.  **Historical trends**: The data set covers a long period (1848-1955) which spans through different technological eras, changes in the electoral system, and two world wars. Therefore, potential newspaper effects could have been driven or absorbed by events marking these periods. Concerning the influence of radio and television, most of the period under investigation spans through an era where print media was the only source of political information. Radio did not get popular in Switzerland until the 1930s and the first television broadcast was only introduced in 1953 (DRS, 2008). However, variation could be present between newspapers active in the pre-radio and the radio era.

4.  **Ideological affiliation**: Muth and Nguyen (2021) investigate the relationship between party affiliated newspapers and party vote share. Related to this, differences might also be observed in newspaper's ability to induce higher electoral participation when distinguishing between ideological affiliations. Until 1917 Switzerland was politically dominated by the liberal-radicals which strongly influenced the design of the constitution of 1848 and hence the Swiss federal system in which cantonal elections are an essential aspect (Schweizer Parlament, n.d.). Newspapers associated with a liberal-radical ideology and thus proponents of liberal-radical politics could have therefore been more supportive of electoral participation compared to other newspapers.

5.  **Media market environment**: the effect might differ with the number of newspapers (i.e., competitors) already present in the media market. Drago et al. [-@drago2014] investigate competition by measuring how the effect of entry and exit varies between the first and subsequent newspapers. If some form of competition is present then the effect should not be limited to the first newspaper in the market. Another case is that an additional newspaper in a market with few papers might impact turnout more than an additional newspaper in a market with many (relative change matters).

The advantage of working with a large data set, both in time and depth, comes along with the challenging task of accounting and controlling for historical events which might influence both the outcome and the independent variable. Coverage of all mentioned aspects would exceed the scope of my thesis. Here, I will focus on three additional research propositions which account for the distinction between political and non-political newspapers, the language diversity of Switzerland and the potential influence of newspaper's ideology before and after Switzerland changed its electoral law in 1919. All these hypothesis are built on the main hypothesis stated above:

I.  **Political newspapers matter**: Since political newspapers are more likely to inform the general public about affairs relevant for their increase voting behavior, they should induce a significantly higher voter turnout than non-political newspapers.

II. **Language matters**: German and French are the predominant languages both in terms of newspapers and language regions. The effects might vary when looking at German vs French newspaper.

III. **Liberal newspapers matter**: Since the political landscape before 1917 was dominated by liberal parties, the estimated coefficient on electoral participation is expected to differ significantly compared to the period after 1919.

An extensive investigation of all ideological types would be interesting but cannot be attempted here. Because liberal newspaper and parties are major players in Swiss political history the focus is set on these. My arguments rely on the widely held working hypothesis that information constitutes the main mechanism for linking newspapers to political participation (Mastuka, 1995). On the individual level, higher education and income have often been identified as the driving forces (Rosenstone, 1980). There is debate on how information incentivizes citizens to vote. One explanation is, that by supplying information to voters, newspapers could simply remind people that an election is pending. Newspapers could also have an indirect effect on turnout by increasing social capital of readers (Genzkow et al. 2011).

The baseline assumption is that on the aggregated canton (federated state) level, readership increases with the number of newspapers. Even though readership numbers are not recorded in the main newspaper data set, evidence from an additional data source (Bürging, 1939) nevertheless shows that newspaper circulation for a subset of years and newspapers strongly increased over time. Following Gentzkow et al. (2011) and Drago et al. (2014), readership is estimated by multiplying newspaper circulation by two, assuming that every copy is read by two individuals (details are provided in the appendix).

In order to test my hypotheses, I employ the **identification strategy** which compares electoral outcomes in cantons that experienced a change in the number of newspapers due to entry or exit (treatment group) to cantons with no change (control group). This strategy is built on the assumption that "exits and entries cause large, discrete changes in newspaper readership" (Gentzkow et al. 2011, p. 2,981). Swiss elections are held at the end of October and thus a newspaper entering in the election year could likely have enough time to supply the market prior to the election (Swiss Parlament, n.d.). For the identification to hold, pre-event trends have to be ruled out since any occurrence of these would indicate correlation between newspapers in the election period and past electoral participation which would then imply the existence of confounding factors.

The **identification assumption** is that cantons with no change represent a valid control group if canton and election fixed effects as well as a set of socio-economic variables are controlled for. In the model, these controls will include population, sector employment and language. In order to test the main hypothesis, the whole set of newspapers is regressed on turnout in different specifications. To test for different subgroups such as political vs non-political or German vs French, as well as for different time periods such as pre-1917 and post-1917, regression is simply repeated on these subgroups and periods. And to test for the influence of market environment, canton-years are first grouped into different quantiles according to the newspapers numbers present in their market.

I find that the net entry of newspapers has a significant positive impact on electoral participation. The impact is larger for political newspapers. German language newspapers exert a positive and significant effect whereas for French language newspapers no significance can be detected. Even stronger positive effects are found when specifying German political and weekly newspapers.

I also show that liberal newspapers were especially important for inducing electoral participation. The effect is positive and significant before 1917 but vanishes after the introduction of the proportional voting system in 1919. However, the results are limited to the inclusion of the top-newspaper-cantons Bern, Vaud and Zürich indicating that the impact of newspapers on voter turnout is largely driven by these cantons.

This thesis mostly contributes to the empirical literature investigating historical political participation in Switzerland. It reevaluates past findings of Muth and Nguyen (2021) and extends the scope of understanding by providing further evidence from previously unexploited data.
